// <auto-generated />
using System;
using Brokerage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Brokerage.Data.Migrations
{
    [DbContext(typeof(BrokerageDbContext))]
    partial class BrokerageDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Brokerage.Core.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CreditLimit")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerUserId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Brokerage.Core.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Brokerage.Data.UsageDailyRow", b =>
                {
                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<long>("AccountsOpened")
                        .HasColumnType("bigint")
                        .HasColumnName("accounts_opened");

                    b.Property<decimal>("DepositVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("deposit_volume");

                    b.Property<long>("Deposits")
                        .HasColumnType("bigint")
                        .HasColumnName("deposits");

                    b.Property<long>("Errors")
                        .HasColumnType("bigint")
                        .HasColumnName("errors");

                    b.Property<long>("Logins")
                        .HasColumnType("bigint")
                        .HasColumnName("logins");

                    b.Property<long>("Requests")
                        .HasColumnType("bigint")
                        .HasColumnName("requests");

                    b.Property<long>("Signups")
                        .HasColumnType("bigint")
                        .HasColumnName("signups");

                    b.Property<decimal>("WithdrawalVolume")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("withdrawal_volume");

                    b.Property<long>("Withdrawals")
                        .HasColumnType("bigint")
                        .HasColumnName("withdrawals");

                    b.HasKey("Date");

                    b.ToTable("usage_daily", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
